import type { OperationalPosition } from '../features/operational_workspace/types';

export function position(overrides: Partial<OperationalPosition> = {}): OperationalPosition {
  return {
    trade_id: 'trade-1',
    position_id: 'position-1',
    product_name: 'Test Warrant',
    product_wkn: 'TEST12',
    product_isin: 'DE000TEST1234',
    underlying_name: 'Test Underlying',
    opened_at: '2026-09-08T08:00:00Z',
    opened_on: '2026-09-08',
    open_quantity: 10,
    average_entry_price: '2.00',
    cost_basis: '20.00',
    realized_gross_pnl: '1.50',
    stop_price: '19000',
    target_price: '20500',
    monitoring_status: 'OK',
    underlying_symbol: 'DAX.INDX',
    valuation_status: 'AVAILABLE',
    product_symbol: 'TEST12.STU',
    valuation_currency: 'EUR',
    market_value: '25',
    unrealized_gross_pnl: '5',
    quote_observed_at: '2026-09-08T08:00:00Z',
    quote_source: 'TEST_PROVIDER',
    open_alert_count: 0,
    open_alert_types: [],
    attention_state: 'OK',
    target: '/trade-management?trade_id=trade-1',
    position_signal: {
      trade_id: 'trade-1',
      position_id: 'position-1',
      alert_level: 'NORMAL',
      attention_required: false,
      quality_status: 'AVAILABLE',
      reason: 'OK',
      candidate_stop: '1.8',
      latest_price: '2.5',
      phase: 'TREND',
      policy_version: 'V1',
      dynamic_stop_policy_version: 'V1',
      analysis_run_id: 'a',
    },
    ...overrides,
  };
}
